spring.application.name=MediCare ERP
server.port=8080
fhir.server.url=http://hapi.fhir.org/baseR4
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.level.ca.uhn.fhir=WARN
logging.level.com.emr=INFO
